/**
 * M11 — LP Rebalancing strategy shared types.
 *
 * All pricing/amount math runs on INTEGER decimal strings / fixed integers
 * (Tick, sqrtPriceX96, liquidity, wei amounts, integer basis points) so the
 * deterministic tick boundaries and profitability math never depend on
 * floating-point arithmetic. Liquidty amounts and pool quantities are surfaced
 * by the blockchain LiquidityAdapter.
 */

/** Token orientation = Token0/token1 order as reported by the pool contract. */
export interface LpPoolState {
  poolAddress: string;
  token0: string;
  token1: string;
  /** Pool fee in integer basis points (e.g. 3000 = 0.3%). */
  feeBps: number;
  /** Uniswap V3 sqrtPriceX96 as a decimal integer string. */
  sqrtPriceX96: string;
  /** The pool's current tick (integer). */
  tick: number;
  /** In-range liquidity (wei integer string). */
  liquidity: string;
  /** 24h volume in USD integer cents. */
  volumeUsdCents: string;
  timestamp: string;
  /** Token decimal places (for human-readable price derivation). */
  decimals0?: number;
  decimals1?: number;
  /** USD price of each token (string to avoid float). */
  token0PriceUsd?: string;
  token1PriceUsd?: string;
  /** Live chain gas estimate in integer USD cents, when available. */
  gasEstimateUsdCents?: string;
  /** False when candidate economics must not be treated as executable. */
  gasEstimateAvailable?: boolean;
}

/** A bound on a position of a single LP NFT. */
export interface LpPosition {
  positionId: string;
  lowerTick: number;
  upperTick: number;
  liquidity: string; // wei integer string
  token0Amount: string; // wei integer string
  token1Amount: string; // wei integer string
  feesUsd: string; // integer USD cents
  timestamp: string;
}

/** A deterministic rebalance candidate surfaced to the AI (bounded set). */
export type LpAction = 'REMOVE' | 'CREATE' | 'REPOSITION';

export interface LpRebalanceSignal {
  action: LpAction;
  poolAddress: string;
  token0: string;
  token1: string;
  /** Existing position this candidate affects (or '' for CREATE). */
  positionId: string;
  /** Deterministically computed new range (never generated by the AI). */
  lowerTick: number;
  upperTick: number;
  /** Reason for the candidate. */
  reason: string;
  /** Candidate metrics (how it scored). */
  feesUsd: string; // integer cents
  estimatedGasUsd: string; // integer cents
  estimatedSlippageUsd: string; // integer cents
  netProfitUsd: string; // integer cents (>0 ⇒ economic rebalance)
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH';
  rank: number;
}

/** Token human-readable orientation (optional — documented for the adapter). */
export type TokenOrientation = 'token0ToToken1' | 'token1ToToken0';

export interface TokenDecimalInfo {
  address: string;
  decimals: number;
}